### ISSUE TITLE
Keyboard shortcut not working

### ISSUE THREAD

**Issue by shekmantang** [getflourish/Sketch-Set-Line-Height-Plugin#1]
On sketch version 3.3.3

**Comment by tomrantala** [comment]
Same thing on version  3.4.2

**Comment by kurtvarner** [comment]
I use this shortcut daily — please, please fix! Version 5.3.1

**Comment by tomrantala** [comment]
+1 here. It's not working on newest Sketch: Version 3.5.1 (25234)

Can you @getflourish please fix this? This is a daily tool for me.

Thanks a lot in advance! :)

**Comment by getflourish** [comment]
Thanks for your reports. It works for me though. Can you make sure, that the shortcut is not triggering a different plugin? For instance, "Fluid", "Data Populator" and "Constraints" seem to use the same cmd + L :/ I hope it’s simply because of that…
