### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [getflourish/Sketch-Set-Line-Height-Plugin#6]
Hi there. As you probably know, `[MSTextLayer lineSpacing]` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `[MSTextLayer lineHeight]` instead, or it won't work in the next release :)

**Comment by getflourish** [comment]
Wish I’d seen this earlier ;) Updated to work with Sketch 40.3 :)
